apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod  # Choose a name
spec:
  acme:
    email: davidalen51@gmail.com  # Set your email
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: alen-letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik